// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Plataforma não suportada: $defaultTargetPlatform',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj389ZkpTZQ7difBl56F5rkcHu65Yth4Y',
    appId: '1:386984799736:web:af521e1323f890a8f8ba0d',
    messagingSenderId: '386984799736',
    projectId: 'bancofintech-957a3',
    authDomain: 'bancofintech-957a3.firebaseapp.com',
    storageBucket: 'bancofintech-957a3.firebasestorage.app',
    measurementId: 'G-F75CKQ1FB6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGTOCQNbwVZSMwwVYVzk0MfMbRYsSP5U',
    appId: '1:386984799736:ios:3ddd890f3dfb39f1f8ba0d',
    messagingSenderId: '386984799736',
    projectId: 'bancofintech-957a3',
    storageBucket: 'bancofintech-957a3.firebasestorage.app',
    iosBundleId: 'com.bancofintech.app.bancoFinTech',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUWbAjGxukFBkXWw0ApLxQROmaojpVCjU',
    appId: '1:386984799736:android:f2698ae4354ec6eff8ba0d',
    messagingSenderId: '386984799736',
    projectId: 'bancofintech-957a3',
    storageBucket: 'bancofintech-957a3.firebasestorage.app',
  );
}
